# Requirements
## Description
A new world organization has just been created. It includes all the museum management committees that have more than 2,000,000 visitors annually. This list is available via __[Wikipedia](https://en.wikipedia.org/wiki/List_of_most_visited_museums)__
This new organization wishes to correlate the tourist attendance at their museums with the population of the respective cities. To achieve this, a small, common and harmonized database must be built to be able to extract features. This DB must include the characteristics of museums as well as the population of the cities in which they are located. You have been chosen to build this database. In addition, you are asked to create a small linear regression ML algorithm to correlate the city population and the influx of visitors.  Your solution must balance the need for quickly assessing the data, rapid prototyping and deploying a MVP to a (potentially) public user that could later scale. You must use the Wikipedia APIs to retrieve this list of museums and their characteristics. You are free to choose the source of your choice for the population of the cities concerned.

## Deliverables
- It is required that your code is a structured Python project. The code should be packaged and exposed in a Docker container (use Docker Compose if you require additional infrastructure).
- A jupyter notebook hosted in docker should also be created. This notebook should  programmatically use your other code to visually present the results of your regression model.

## Notes
You will be evaluated not only on how your code works but also on the rationale for the choices you make. you make.

# Workplan
1. Setup Jupyter server
2. Investigate wikipedia Python API
3. Implement a simple wrapper for fetching the required data into CSV files
4. Choose a "database" or simple CSV file
5. Implement a way to incrementally add to CSV file
6. Implement a simple script to reload the CSV file
7. Implement a simple ML regression algorithm that learns and saves the parameters
8. Implement a simple ML script that evaluates a value
9. Setup Docker

# Execution

## Jupyter setup

- Configuration directory environment var: JUPYTER_CONFIG_DIR
-

## Set the device

In [1]:
import torch
dtype = torch.float
device = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Platform running on {device} device")

Platform running on cuda device

In [104]:
import importlib
import museums
importlib.reload(museums)
museums.download_data()

Getting page List_of_most-visited_museums, section 1 from Wikipedia
1 Downloading
2 Extracting content
3 Parsing content
4 Success
Getting page List_of_largest_cities, section 5 from Wikipedia
1 Downloading
2 Extracting content
3 Parsing content
4 Success

In [105]:
museums.museum_data

,name,location,visitors
0,Louvre,"Paris, France","7,726,321[1][2]"
1,Vatican Museums,Vatican City,"5,080,866[1]"
2,Natural History Museum,"London, United Kingdom","4,654,608[3]"
3,British Museum,"London, United Kingdom","4,097,253[1][3]"
4,National Museum of Natural History,"Washington, D.C., United States","3,900,000[4]"
...,...,...,...
66,Guggenheim Museum Bilbao,"Bilbao, Spain","1,289,147[1]"
67,Scottish National Gallery,"Edinburgh, United Kingdom","1,277,230[1]"
68,National Gallery Singapore,Singapore,"1,262,189[1]"
69,Museo Reina Sofía,"Madrid, Spain","1,253,183[d][1]"
70,Museum of European and Mediterranean Civilisat...,"Marseille, France","1,251,030[1]"

In [106]:
museums.city_data

           city        country  population
1         Tokyo          Japan    37468000
2         Delhi          India    28514000
3      Shanghai          China    25582000
4     São Paulo         Brazil    21650000
5   Mexico City         Mexico    21581000
..          ...            ...         ...
77   Washington  United States     5207000
78       Yangon        Myanmar     5157000
79   Alexandria          Egypt     5086000
80        Jinan          China     5052000
81  Guadalajara         Mexico     5023000

[81 rows x 3 columns]

In [108]:
museums.create_master_data()
museums.master_data

Louvre: Paris,  France, 7726321, 10901000
Vatican Museums: Rome, Italy, 5080866, nan
Natural History Museum: London,  United Kingdom, 4654608, 9046000
British Museum: London,  United Kingdom, 4097253, 9046000
National Museum of Natural History: Washington, Unitesd States, 3900000, 5207000
Tate Modern: London,  United Kingdom, 3883160, 9046000
National Museum of Korea: Seoul,  South Korea, 3411381, 9963000
Guangdong Museum: Guangzhou,  China, 3359700, 12638000
Mevlana Museum: Konya,  Turkey, 3352505, nan
Musée d'Orsay: Paris,  France, 3270182, 10901000
National Gallery of Art: Washington, Unitesd States, 3256433, 5207000
Metropolitan Museum of Art: New York City,  United States, 3208832, nan
Centre Pompidou: Paris,  France, 3009570, 10901000
State Hermitage Museum: Saint Petersburg,  Russia, 2812913, 5383000
National Gallery: London,  United Kingdom, 2727119, 9046000
State Russian Museum: Saint Petersburg,  Russia, 2651688, 5383000
National Museum of Marine Science and Technology: Keelung,  Taiwan, 2582444, nan
Prado Museum: Madrid,  Spain, 2456724, 6497000
Victoria and Albert Museum: London,  United Kingdom, 2370261, 9046000
London Science Museum: London,  United Kingdom, 2334930, 9046000
Chinese Aviation Museum: Beijing,  China, 2300000, 19618000
National Museum of Natural Science: Taichung,  Taiwan, 2299808, nan
Galleria degli Uffizi: Florence,  Italy, 2222692, nan
Museum of Modern Art: New York City,  United States, 2190440, nan
Topography of Terror: Berlin,  Germany, 2100000, nan
M+: Hong Kong,  China, 2034331, 7429000
Opium War Museum [zh]: Dongguan,  China, 2025800, 7360000
Cité des Sciences et de l'Industrie: Paris,  France, 1992823, 10901000
National Museum of Scotland: Edinburgh,  United Kingdom, 1973751, nan
State Tretyakov Gallery: Moscow,  Russia, 1910000, 12410000
National Taiwan Science Education Center: Taipei,  Taiwan, 1878504, nan
National Science and Technology Museum: Kaohsiung,  Taiwan, 1875372, nan
National Museum of Modern and Contemporary Art: Seoul,  South Korea, 1806641, 9963000
Smithsonian Museum of American History: Washington, Unitesd States, 1800000, 5207000
Rijksmuseum: Amsterdam,  Netherlands, 1766084, nan
California Science Center: Los Angeles,  United States, 1694000, 12458000
National Museum of China: Beijing,  China, 1630911, 19618000
Royal Museums Greenwich: London,  United Kingdom, 1628580, 9046000
Nanjing Museum: Nanjing,  China, 1610000, 8245000
Zhejiang Museum of Natural History: Hangzhou,  China, 1581263, 7236000
National Gallery of Victoria: Melbourne,  Australia, 1580303, nan
Jianchuan Museum Cluster: Chengdu,  China, 1538143, 8813000
Houston Museum of Natural Science: Houston,  United States, 1520000, 6115000
Tokyo Metropolitan Art Museum: Tokyo,  Japan, 1509970, 37468000
Changzhou Museum: Changzhou,  China, 1508229, nan
Humboldt Forum: Berlin,  Germany, 1500000, nan
National Museum of Anthropology: Mexico City,  Mexico, 1494587, 21581000
National Museum of History: Mexico City,  Mexico, 1486379, 21581000
National Air and Space Museum[b]: Washington, Unitesd States, 1486000, 5207000
Kaohsiung Museum of Fine Arts: Kaohsiung,  Taiwan, 1461406, nan
Acropolis Museum: Athens,  Greece, 1451727, nan
China Science and Technology Museum: Beijing,  China, 1431189, 19618000
Galleria dell'Accademia: Florence,  Italy, 1428369, nan
Suzhou Museum: Suzhou,  China, 1417412, 6339000
Chengdu Museum: Chengdu,  China, 1404735, 8813000
Shanghai Science and Technology Museum: Shanghai,  China, 1403179, 25582000
The National Art Center, Tokyo: Tokyo,  Japan, 1400096, 37468000
Louis Vuitton Foundation: Paris,  France, 1398525, 10901000
Tokyo National Museum: Tokyo,  Japan, 1372132, 37468000
National Museum, Krakow: Krakow,  Poland, 1365425, nan
Centro Cultural Banco do Brasil: São Paulo,  Brazil, 1364208, 21650000
Van Gogh Museum: Amsterdam,  Netherlands, 1364023, nan
National Museum of Nature and Science: Tokyo,  Japan, 1350000, 37468000
Kunsthistorisches Museum: Vienna,  Austria, 1345617, nan
Tianjin Natural History Museum: Tianjin,  China, 1320752, 13215000
Palacio de Cristal del Retiro: Madrid,  Spain, 1318823, 6497000
Guggenheim Museum Bilbao: Bilbao,  Spain, 1289147, nan
Scottish National Gallery: Edinburgh,  United Kingdom, 1277230, nan
National Gallery Singapore: Singapore, Singapore, 1262189, 5792000
Museo Reina Sofía: Madrid,  Spain, 1253183, 6497000
Museum of European and Mediterranean Civilisations: Marseille,  France, 1251030, nan

,name,city,country,visitors,population
0,Louvre,Paris,France,7726321,10901000.0
1,Vatican Museums,Rome,Italy,5080866,NaN
2,Natural History Museum,London,United Kingdom,4654608,9046000.0
3,British Museum,London,United Kingdom,4097253,9046000.0
4,National Museum of Natural History,Washington,Unitesd States,3900000,5207000.0
...,...,...,...,...,...
66,Guggenheim Museum Bilbao,Bilbao,Spain,1289147,NaN
67,Scottish National Gallery,Edinburgh,United Kingdom,1277230,NaN
68,National Gallery Singapore,Singapore,Singapore,1262189,5792000.0
69,Museo Reina Sofía,Madrid,Spain,1253183,6497000.0
70,Museum of European and Mediterranean Civilisat...,Marseille,France,1251030,NaN

In [ ]:
[]